baseurl = "https://example.org/"
title = "Icarus-statnmap"
# Enable comments by entering your Disqus shortname
disqusShortname = "spf13"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
# Define the number of posts per page
paginate = 10
footnotereturnlinkcontents = "↩"
theme = "hugo-statnmap-theme"
# Uncomment the themesDir option if you do not use this theme in production
# themesDir = "../.."


[permalinks]
    post = "/:year/:month/:day/:slug"


[params]
    # Tell me who you are
    author = "John Doe"
    bio = "Blogger - Programmer - Gopher"
    location = "Earth"
    site_description = ""
    copyright  = "Powered by [Hugo](//gohugo.io). Theme by [PPOffice](http://github.com/ppoffice)."
    avatar = "css/images/avatar.png"
    # Enter your email address to display your Gravatar icon in the profile. If not set the theme
    # will fallback to the avatar.
    gravatar = "you@example.com"
    logo = "css/images/logo.png"
    squarelogo = "css/images/logo.png"
    # sitelogo = "images/Logo_EN_centered_500dpi.png"
    sitelogo = ""
    # Only for small devices
    logolong = "css/images/logo.png"
    
    # Set to true to disable code folding
    disable_codefolding = false
    # Set to "hide" or "show" all codes by default
    codefolding_show = "hide"
    # Code blocks to apply code folding
    codeblocks = ["pre.sourceCode", "pre.r", "pre.python", "pre.bash", "pre.sql", "pre.cpp", "pre.stan", "pre.js", "pre.css", "pre.html", "pre.yaml"]
    
    disable_mathjax = false # set to true to disable MathJax
    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"
    
    # options for highlight.js (version, additional languages, and theme)
    disable_highlight = false
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
    
    # How to cite blog article
    disable_citation = false
    citation_author = "Author A"
   
    # define which types of pages should be shown. By default the type with the most regular pages
    mainSections = ["post"]

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

    # Add custom assets with their paths relative to the static folder
	  custom_css = []
	  custom_js  = []

    # Optional Params
    # The set of favicons used are based on the write-up from this link:
    # https://github.com/audreyr/favicon-cheat-sheet
    # You can also add a favicon.ico container at the root of "static" folder
    # Please see the favicon partial template for more information
    # 1 - Create a favicon folder in "static".
    # 2 - Create a favicon with 250*250px and 300*300px, named
    # favicon-250.png and favicon-300.png
    loadFavicon          = false

    # Number of words of post summary
    summary_length = 200

# Create custom menu entries by defining a name and a url for
# them. Since you can also link posts, you can use the weight
# to define order of appearance.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
#
# You can define menu names according to the translation
# See <https://gohugo.io/content-management/multilingual/#configuring-multilingual-mode>
# for more information
DefaultContentLanguage = "en"
  
[Taxonomies]
  tag = "tags"
  category = "categories"
  sticky = "stickies"

[Languages]
[Languages.en]
LanguageName = "English"
title = "hugo-statnmap-theme"
bio = "A wordpress twenty-fifteen like theme"
weight = 1

[[Languages.en.menu.main]]
name   = "Home"
url    = "/"
weight = 1

[[Languages.en.menu.main]]
name = "Blog"
url = "/post/"
weight = 2

[[Languages.en.menu.main]]
name = "Sticky"
url = "/stickies/"
weight = 2

[[Languages.en.menu.main]]
name = "StickyPages"
url = "/stickypages/"
weight = 2

[[Languages.en.menu.main]]
name = "Contact"
url = "/contact/"
weight = 5

[Languages.fr]
LanguageName = "Français"
title = "hugo-statnmap-theme fr"
bio = "A wordpress twenty-fifteen like theme"
weight = 2

[[Languages.fr.menu.main]]
name   = "Accueil"
url    = "/"
weight = 1

[[Languages.fr.menu.main]]
name = "Blog"
url = "/blog/"
weight = 2

[[Languages.fr.menu.main]]
name = "Contact"
url = "/contact/"
weight = 5

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://github.com/digitalcraftsman"


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = "digitalcraftsman"
    gitlab          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "spf13"
    googlescholar   = ""
    orcid           = ""
    researchgate    = ""
    email           = ""

    

# Enable and disable widgets for the right sidebar
[params.widgets]
    language_switcher = true
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true

# Set the followings to true as part of your site SEO
enableRobotsTXT = true
canonifyURLs = true
